### ISSUE TITLE
vec3.h cross product - clarify

### ISSUE THREAD

**Issue by arrudenk** [RayTracing/InOneWeekend#16] opened 2018-09-27 22:10 UTC
Hello Peter.
I have some question about Your "cross product" function.
wiki version of "cross product" is:
a×b=⟨a2*b3−a3*b2,  a3*b1 − a1*b3, a1*b2 − a2*b1⟩
and Your is:
a×b=⟨a2*b3−a3*b2,  _-(a3*b1 − a1*b3)_,  a1*b2 − a2*b1⟩
I'd be very grateful if You explain why your "**y**" is negative

**Comment by hollasch** [comment] 2018-09-27 22:42
From `vec3.h[101]`, the code for the Y component is

    (-(v1.e[0]*v2.e[2] - v1.e[2]*v2.e[0])),

So a1=`v1.e[0]`, a3=`v1.e[2]`, b1=`v2.e[0]`, and b3=`v2.e[2]`. Thus, the above is equivalent to

    (-(a1*b3 - a3*b1)),

which reduces to

    a3b1 - a1b3

which matches the wiki.

**Comment by hollasch** [comment] 2019-06-29 08:02
I'll second @FocusGFX's idea. A tiny bit more clear.

**Comment by hollasch** [comment] 2019-06-29 08:09
Duplicate of #10. Keeping this one for the more fleshed out comment thread.

**Comment by ronaldfw** [comment] 2019-08-23 05:33
Happy to take this and make the code and book changes.

**Closed** 2019-08-23 18:43 UTC
Labels: book, code
